- api/index.js
Chicos solo estoy probando esto y solo he puesto una  linea de comentario
> agregando comentario

- api/src/db.js
- api/src/models/Menu.js
- api/src/models/Tipo.js
Creada la tabla menu + las relaciones con las otras tablas
> Branch david

- api/.env
- api/src/controllers/index.js
- api/src/controllers/postTipo.js
- api/src/controllers/tipoController.js
- api/src/routes/index.js
agregados los get y post del tipo
> get y post tipo

- api/.gitignore
- api/src/app.js
- api/src/controllers/createMenuController.js
- api/src/controllers/especialidadController.js
- api/src/controllers/findMenuByIdController.js
- api/src/controllers/index.js
- api/src/controllers/menuController.js
- api/src/controllers/postEspecialidad.js
- api/src/controllers/postTipo.js
- api/src/db.js
- api/src/models/Especialidad.js
- api/src/models/Menu.js
- api/src/models/Tipo.js
- api/src/routes/index.js
agregados post y by id de menu
> Branch santi

- api/.env
- api/.gitignore
- api/index.js
- api/src/controllers/index.js
- api/src/controllers/updateTipoController.js
- api/src/db.js
- api/src/models/Role.js
- api/src/models/User.js
- api/src/routes/index.js
agregdo update de tipo
agregados modelos de user y rol
agregada base de datos deployada al env y al db
> agregado updateTipo y modelos user y role y db deployada

- api/src/controllers/deleteTipoController.js
- api/src/controllers/index.js
- api/src/db.js
- api/src/routes/index.js
arreglado el id faltante en la ruta y agregado delete
> arreglado el id faltante  en la ruta y hecho el delete

- api/.env
- api/package-lock.json
- api/package.json
- api/src/controllers/bcryptController.js
- api/src/controllers/index.js
- api/src/controllers/loginController.js
- api/src/controllers/postRoleController.js
- api/src/controllers/registerController.js
- api/src/controllers/tipoController.js
- api/src/db.js
- api/src/models/User.js
- api/src/routes/index.js
agregdo post de rol, login y register de user
> agregdo post de rol, login y register de user

- api/src/controllers/getMenusByQuery.js
- api/src/controllers/index.js
- api/src/routes/index.js
cree la ruta y el controller para el buscador a traves de un query mi rey
> Rama temporal

- api/src/controllers/index.js
- api/src/controllers/updateMenu.js
- api/src/routes/index.js
> David remoto

- api/src/app.js
- api/src/controllers/TipoController/updateTipoController.js
- api/src/models/Tipo.js
- api/src/models/User.js
> corregidos modelos

- api/src/controllers/MenuController/deleteMenuController.js
- api/src/controllers/MenuController/menuController.js
- api/src/controllers/index.js
- api/src/routes/index.js
> ruta para el borrador lógico

- api/src/controllers/EspecController/deleteEspecNoAsoc.js
- api/src/controllers/TipoController/deleteTipoNoAsociado.js
- api/src/routes/index.js
> arreglda barra y otros

- api/src/controllers/ReviewsController/getReviewsByStatus.js
- api/src/controllers/ReviewsController/postReview.js
- api/src/controllers/ReviewsController/updateReview.js
- api/src/controllers/ReviewsController/updateReviewStatus.js
- api/src/controllers/StatusController/addStatus.js
- api/src/controllers/StatusController/getStatus.js
- api/src/controllers/StatusController/getStatusById.js
- api/src/controllers/StatusController/updateStatus.js
- api/src/controllers/index.js
- api/src/routes/index.js
agregados arreglos en los controllers
> review y status controllers

- api/src/controllers/AuthController/registerController.js
- api/src/controllers/ReviewsController/getAllAvg.js
- api/src/controllers/UserController/updateUser.js
- api/src/controllers/index.js
- api/src/routes/index.js
> agregado all avg

- api/src/controllers/CarritoController/getCarrito.js
- api/src/controllers/CarritoController/postCarrito.js
- api/src/controllers/index.js
- api/src/db.js
- api/src/models/Carrito.js
- api/src/models/Orden.js
- api/src/routes/index.js
Rutas y controlador de carrito
> rutas y controlador de carrito

- api/src/models/Review.js
> allow true

- api/src/controllers/OrdenController/getDireccionByUser.js
- api/src/controllers/OrdenController/getEnvioByDire.js
- api/src/controllers/OrdenController/getOrden.js
- api/src/controllers/OrdenController/getOrdenByUser.js
- api/src/controllers/OrdenController/postDireccion.js
- api/src/controllers/OrdenController/postEnvio.js
- api/src/controllers/OrdenController/postOrden.js
- api/src/controllers/index.js
- api/src/db.js
- api/src/models/Direccion.js
- api/src/models/Envio.js
- api/src/models/Orden.js
- api/src/routes/index.js
agregado
- orden
- envio
- direccion
> agregado orde direccion y envio

- api/src/controllers/ReviewsController/getAllReviews.js
> modificado allreviews

- api/src/routes/index.js
> reparado delete logico

- api/src/controllers/CarritoController/updateCantidadCarrito.js
le agregue una funcionalidad a una ruta del back
> cambie una funcionalidad en la ruta update carrito

- api/src/controllers/EnvioController/deleteDiresByUser.js
- api/src/controllers/index.js
- api/src/models/Envio.js
- api/src/models/Menu.js
- api/src/models/Orden.js
- api/src/models/Status.js
- api/src/models/Tipo.js
- api/src/routes/index.js
> agregado delete dires

- api/src/controllers/EnvioController/deleteDireById.js
- api/src/controllers/EnvioController/updateDireById.js
- api/src/controllers/UserController/updatePassword.js
- api/src/controllers/index.js
- api/src/routes/index.js
> delete y update dire by id

- api/src/controllers/OrdenController/getOrden.js
- api/src/controllers/PaymentController/createPaymentLink.js
- api/src/controllers/PaymentController/receiveWebHook.js
- api/src/controllers/ReviewsController/getReviewsByUser.js
- api/src/db.js
- api/src/models/Envio.js
- api/src/models/Orden.js
re agregado envios y props de orden
> re agregado envios y props de orden

- api/src/controllers/OrdenController/getOrdenByUserByDate.js
- api/src/controllers/PaymentController/createPaymentLink.js
- api/src/controllers/index.js
- api/src/models/Orden.js
- api/src/routes/index.js
agregado controller y direccion a orden
> agregado controller y direccion a orden

- api/src/controllers/OrdenController/getOrdenByUserByDate.js
- api/src/controllers/OrdenController/getOrdenByUserByDate2.js
- api/src/controllers/PaymentController/createPaymentLink.js
- api/src/controllers/PaymentController/receiveWebHook.js
- api/src/controllers/index.js
- api/src/routes/index.js
agregada data al orden controller y camiado 400 por 200
> agregada data al orden controller y camiado 400 por 200

- api/src/controllers/UserController/getUsersBanned.js
- api/src/controllers/UserController/updateBanned.js
> sacados los admin

- api/src/controllers/AuthController/registerController.js
- api/src/controllers/PaymentController/createPaymentLink.js
- api/src/controllers/UserController/getAllUsers.js
- api/src/controllers/index.js
- api/src/routes/index.js
> agregado el if para los mails

- api/src/controllers/PaymentController/createPaymentLink.js
> link del webhook

- api/src/controllers/PaymentController/receiveWebHook.js
> res eliminado
